dist: trusty

os: linux

language: node_js

node_js: '10.15.0'

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - npm install -g yarn
install: yarn install --frozen-lockfile

jobs:
  include:
    # Run tests in parallel
    - stage: test
      script: yarn check:licenses
    - script: yarn check:security
    - script: yarn test:lint
    - script: yarn test:unit:ci
      # Upload coverage reports to Codecov
      after_success: yarn coverage-upload -t ${CODECOV_TOKEN}
    - stage: publish
      script: skip
      # Publish package to NPM
      before_deploy: yarn predeploy
      deploy:
        # Publish Circuit UI to NPM
        - provider: script
          on:
            all_branches: true
          script: yarn release
        # Deploy Storybook to GitHub Pages
        - provider: pages
          token: $GITHUB_TOKEN
          on:
            all_branches: true
            # branch: master
          local_dir: public
          target_branch: gh-pages
